version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ACCB72A231B3BFE22361B62CBE9019611B691201FFA00F9602BB1FFAC67E+Mb2
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  backend:
    build: ../server   # Adjust path if needed (relative to this yml file)
    environment:
      - DB_USER=SA
      - DB_PASSWORD=ACCB72A231B3BFE22361B62CBE9019611B691201FFA00F9602BB1FFAC67E+Mb2
      - DB_SERVER=db
      - DB_DATABASE=MRE
      - DB_PORT=1433
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

  frontend:
    build: ../mre-vite   # Adjust path if needed
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    entrypoint: /bin/bash
    command: >
      -c "
      for i in {1..30}; do
        /opt/mssql-tools/bin/sqlcmd -S db -U SA -P 'ACCB72A231B3BFE22361B62CBE9019611B691201FFA00F9602BB1FFAC67E+Mb2' -Q 'SELECT 1' && break || sleep 2;
      done &&
      /opt/mssql-tools/bin/sqlcmd -S db -U SA -P 'ACCB72A231B3BFE22361B62CBE9019611B691201FFA00F9602BB1FFAC67E+Mb2' -i /init.sql
      "
    volumes:
      - ./init.sql:/init.sql
    restart: "no"

volumes:
  mssqldata: