IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'MRE')
BEGIN
  CREATE DATABASE MRE;
END
GO

USE MRE;
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = N'Users')
BEGIN
  CREATE TABLE Users (
    Id INT IDENTITY PRIMARY KEY,
    UserName NVARCHAR(256) NOT NULL,
    FullName NVARCHAR(256) NOT NULL
  );
END
GO